### ISSUE TITLE
Small typo in the Makefile.

### ISSUE THREAD

**Issue by tfarina** [Gottox/bgs#4]
In the first line it says: "dynamic window manager", instead of "back ground setter".

**Comment by wifiextender** [comment]
@tfarina I guess if you delve further into the [dwm] (http://dwm.suckless.org/) project you'll find the answer.

I was looking for dead simple background setter for a long time, nitrogen is pretty much overkiller, so hats off to @Gottox for utilizing the `dwm' codebase as starting point.

**Comment by Gottox** [comment]
awkward... But to make things clear: source is completely written by me, only the Makefile is from suckless.

**Comment by wifiextender** [comment]
I can't agree with you as your source code is 99% identical to the one in `dwm'.

If needed I can copy and paste every single line of your source code here, and do line by line comparison.

As I said, I am grateful for your work and the fact that you have utilized their codebase.

**Comment by Gottox** [comment]
Well, I used to be an active dwm contributor. And why should I do things differently if they're good? :)

**Comment by wifiextender** [comment]
I'm not against reusing someone else's codebase or part of it.
I did contributed [statusbar] (http://dwm.suckless.org/dwmstatus/dwm-bar.c) program too.
